### ISSUE TITLE
Spacing scale

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-base#10]
We've talked in the past about adding a spacing scale so that we can have more consistent padding, margin, etc. across our components. 

Something like tailwind's spacing might work. Also, something that the apps group web devs use and a nice to have for them to use calcite-components.

https://tailwindcss.com/docs/customizing-spacing#default-spacing-scale

**Comment by TheBlueDog** [comment]
Tracking.

**Comment by julio8a** [comment]
This is done #23
